# -*- coding: utf-8 -*-
"""Store Inventory Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_eBXlYIoJtd-EMAsG-n-j0lJutJAOzmk

## Imports, Settings and Functions
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#ML Libs
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split

def create_sequences(data, target_col, window_size):
    X, y = [], []
    for i in range(len(data) - window_size):
        X.append(data[i:i+window_size])
        y.append(data[i+window_size][target_col])
    return np.array(X), np.array(y)

"""## Reading Data"""

path = 'sample_data/retail_store_inventory.csv'

inventory = pd.read_csv(path)

inventory.head()

inventory.columns

inventory.describe()

inventory['Date']= pd.to_datetime(inventory['Date'])

daily_sales = inventory.groupby('Date')['Units Sold'].sum().reset_index()

plt.figure(figsize=(12, 6))
plt.plot(daily_sales['Date'], daily_sales['Units Sold'])
plt.title('Time series plot of daily sales')
plt.xlabel('Date')
plt.ylabel('Units Sold')
plt.show()

"""## Data Modeling"""

inventory = inventory.sort_values(['Store ID', 'Product ID', 'Date'])

"""### Transforming Features"""

categorical_cols = ['Category', 'Region', 'Weather Condition', 'Holiday/Promotion', 'Seasonality']
numerical_cols = ['Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Competitor Pricing']

# features categóricas
for col in categorical_cols:
    inventory[col] = LabelEncoder().fit_transform(inventory[col])

# features numéricas
scaler = MinMaxScaler()
inventory[numerical_cols] = scaler.fit_transform(inventory[numerical_cols])

inventory.head()

grouped = inventory.groupby(['Store ID', 'Product ID'])

X_all, y_all = [], []

for _, group in grouped:
    group = group.sort_values('Date')
    group = group.drop(columns=['Date', 'Store ID', 'Product ID'])
    values = group.values
    X, y = create_sequences(values, target_col=group.columns.get_loc('Units Sold'), window_size=30)
    X_all.append(X)
    y_all.append(y)

X_all = np.concatenate(X_all)
y_all = np.concatenate(y_all)

"""## LSTM Model"""

model = Sequential()
model.add(LSTM(units=64, activation='relu', input_shape=(30, X_all.shape[2])))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse')
model.summary()

X_train, X_val, y_train, y_val = train_test_split(X_all, y_all, test_size=0.2, shuffle=False)

model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_val, y_val))

y_pred = model.predict(X_val)

print("MAE:", mean_absolute_error(y_val, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_val, y_pred)))

y_pred_flat = y_pred.flatten()

plt.figure(figsize=(12, 6))
plt.plot(y_val, label='Real', color='blue')
plt.plot(y_pred_flat, label='Previsto (LSTM)', color='orange')

plt.title('Comparação entre Valores Reais e Previstos - LSTM')
plt.xlabel('Dias')
plt.ylabel('Unidades Vendidas (normalizadas)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

n = 200

plt.figure(figsize=(12, 6))
plt.plot(y_val[-n:], label='Real', color='blue')
plt.plot(y_pred.flatten()[-n:], label='Previsto', color='orange')

plt.title(f'Comparação dos últimos {n} dias')
plt.xlabel('Dias')
plt.ylabel('Unidades Vendidas (normalizadas)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()