# -*- coding: utf-8 -*-
"""Marketing A/B Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqEWiLXvQgGOJw2E7rOvu97wTJoeq7Ra

#**Marketing A/B Testing**

According to Kaggle:

> The idea of the dataset is to analyze the groups, find if the ads were successful, how much the company can make from the ads, and if the difference between the groups is statistically significant.


###**Data dictionary:**

`user_id:` User ID (unique)

`test_group:` If "ad" (proposal) the person saw the advertisement, if "psa" (baseline) they only saw the public service announcement

`converted:` If a person bought the product then True, else is False

`total_ads:` Amount of ads seen by person

`most_ads_day:` Day that the person saw the biggest amount of ads

`most_ads_hour:` Hour of day that the person saw the biggest amount of ads

## Imports, deps and settings
"""

pip install kaggle -q

pip install memory-profiler -q

import kagglehub
from kagglehub import KaggleDatasetAdapter
from google.colab import files
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.stats.proportion import proportions_ztest

"""### Kaggle Settings"""

files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""### Saving Datasets"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/

!kaggle datasets download faviovaz/marketing-ab-testing

!unzip marketing-ab-testing.zip -d marketing-ab-testing

"""## Data Modeling"""

ab_testing_df = pd.read_csv('/content/marketing-ab-testing/marketing_AB.csv')

"""### Summary"""

ab_testing_df.head()

conversion_summary = (
    ab_testing_df
    .groupby('test group')['converted']
    .agg(['mean', 'count', 'sum'])
  )

cr_baseline = conversion_summary.loc['psa', 'mean']
cr_proposal = conversion_summary.loc['ad', 'mean']

count_baseline = conversion_summary.loc['psa', 'count']
count_proposal = conversion_summary.loc['ad', 'count']

sum_baseline = conversion_summary.loc['psa', 'sum']
sum_proposal = conversion_summary.loc['ad', 'sum']


print(f'Baseline conversion rate: {cr_baseline:.4f}')
print(f'Proposal conversion rate: {cr_proposal:.4f}')

print(f'Baseline count: {count_baseline}')
print(f'Proposal count: {count_proposal}')

print(f'Baseline sum: {sum_baseline}')
print(f'Proposal sum: {sum_proposal}')

"""### **Significância Estatística**

**Entendendo:** A Significância Estatística mede se o resultado observado em um experimento (ex: diferença entre grupo de controle e grupo de teste) pode ser explicado apenas pelo acaso ou se provavelmente é um efeito real.


---


**Z-Test:** teste estatístico que compara duas proporções ou duas médias para verificar se a diferença observada é significativa. Se |Z| for grande → diferença improvável de ser acaso.


---


**p-valor:** probabilidade condicional de observar um valor da estatística de teste igual ou mais extremo que o observado, dado que a hipótese nula H₀ é verdadeira.

p-valor pequeno (ex: < 0,05)
→ Diferença difícil de ocorrer por acaso
→ Rejeitamos H₀ → efeito é estatisticamente significativo


p-valor grande (ex: > 0,05)
→ Diferença provavelmente aconteceu por acaso
→ Não rejeitamos H₀ → efeito não é confiável
"""

count = [sum_proposal, sum_baseline]
nobs  = [count_proposal, count_baseline]

z_stat, p_value = proportions_ztest(count, nobs, alternative='two-sided')

print(f"Z={z_stat:.3f}")
print(f"p-valor={p_value:.4f}")

# Como o Z deu um valor alto e p p-valor ficou como zero, podemos assumir que o teste é estatisticamente significativo, e podemos passar para outras análises.

"""### **Lift**

**Entendendo o lift:** O lift mede o ganho percentual que o grupo de teste teve em relação ao controle.

Lift = (Conversão Proposal - Conversão Baseline) / Conversão Baseline

**Lift positivo (>0):** o teste aumentou a taxa de conversão.

**Lift negativo (<0):** o teste piorou a conversão.

**Lift zero (=0):** não houve diferença.
"""

lift = (cr_proposal - cr_baseline) / cr_baseline

print(f'Lift: {lift:.2%}')

# Dado que nosso lift ficou em 43.09%, o grupo de teste performou significativamente melhor do que o grupo de controle.