# -*- coding: utf-8 -*-
"""battle_of_libs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pNP6R3EAG7EcUD6dgNYUW3oKRzGfX9xR

# **Battle of Libs**

📘 **Notebook Description**

This notebook presents a comparative analysis of three powerful data processing libraries: **Pandas, Polars, and DuckDB**. Using the New York City Taxi Trip dataset, from Kaggle, I evaluate and benchmark each tool across various dimensions such as:

* Data loading speed

* Memory usage

* Syntax clarity and developer experience

The goal is to understand the strengths and trade-offs of each library in the context of real-world data exploration and transformation tasks.

## Imports, deps and settings
"""

pip install kaggle -q

pip install memory-profiler -q

import kagglehub
from kagglehub import KaggleDatasetAdapter
from google.colab import files
import pandas as pd
import polars as pl
import duckdb as db
from pathlib import Path
from datetime import datetime
from memory_profiler import memory_usage
import seaborn as sns
import matplotlib.pyplot as plt

"""### Kaggle Settings"""

files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/

!kaggle datasets download microize/newyork-yellow-taxi-trip-data-2020-2019

"""### Saving Datasets"""

!unzip newyork-yellow-taxi-trip-data-2020-2019.zip -d newyork-yellow-taxi-trip-data

#files list

folder = Path('/content/newyork-yellow-taxi-trip-data')
files = [f.name for f in folder.iterdir() if f.is_file()]

"""## Pandas"""

dfs = []

for file in files:

  df = pd.read_csv(f'/content/newyork-yellow-taxi-trip-data/{file}')
  filtered_df = df[df['tip_amount'] > 0]
  dfs.append(filtered_df)


base_df = pd.concat(dfs, ignore_index=True)
base_df['tpep_pickup_datetime'] = pd.to_datetime(base_df['tpep_pickup_datetime'])
base_df['hour'] = base_df['tpep_pickup_datetime'].dt.hour

tip_mean_per_hour = base_df.groupby('hour')['tip_amount'].mean()

"""### Gorjeta média por Horário"""

print(tip_mean_per_hour)

"""### To Parquet"""

start = datetime.now()

def save_parquet():
  (
    tip_mean_per_hour
    .to_frame()
    .to_parquet('/content/parquet_files/tip_mean_per_hour_pandas.parquet')
  )

mem_usage = memory_usage(save_parquet)

end = datetime.now()

time_in_sec = (end - start).total_seconds()

results_df = pd.DataFrame({
  'lib': ['pandas'],
  'max_memory_use': [max(mem_usage)],
  'min_memory_use': [min(mem_usage)],
  'total_memory_use': [max(mem_usage) - min(mem_usage)],
  'time_in_sec': [time_in_sec]
})

"""## Polars"""

dfs = []

for file in files:
  df = pl.read_csv(
    f'/content/newyork-yellow-taxi-trip-data/{file}',
    infer_schema_length=10000,
    schema_overrides={
      'tip_amount': pl.Float64,
      'tolls_amount': pl.Float64,
      'fare_amount': pl.Float64,
      'total_amount': pl.Float64,
    }
  )

  filtered_df = df.filter(pl.col('tip_amount') > 0)

  dfs.append(filtered_df)

base_df = pl.concat(dfs)

base_df = (
  base_df
  .with_columns([pl.col('tpep_pickup_datetime').str.to_datetime().alias('tpep_pickup_datetime')])
  .with_columns([pl.col('tpep_pickup_datetime').dt.hour().alias('hour')])
)

tip_mean_per_hour = (
  base_df
  .group_by('hour')
  .agg(
    pl.col('tip_amount').mean().alias('tip_amount_mean')
    )
)

"""### Gorjeta média por Horário"""

print(tip_mean_per_hour)

"""### To Parquet"""

start = datetime.now()

def save_parquet():
  (
    tip_mean_per_hour
    .write_parquet("/content/parquet_files/tip_mean_per_hour_polars.parquet")
  )

mem_usage = memory_usage(save_parquet)

end = datetime.now()

time_in_sec = (end - start).total_seconds()

results_polars_df = pd.DataFrame({
  'lib': ['polars'],
  'max_memory_use': [max(mem_usage)],
  'min_memory_use': [min(mem_usage)],
  'total_memory_use': [max(mem_usage) - min(mem_usage)],
  'time_in_sec': [time_in_sec]
})

results_df = pd.concat([results_df, results_polars_df], ignore_index=True)

"""## DuckDB"""

con = db.connect(database=':memory:')

base_path = '/content/newyork-yellow-taxi-trip-data'

for i, file in enumerate(files):
    path = f"{base_path}/{file}"

    query = f"""
        SELECT
          *,
          EXTRACT(HOUR FROM tpep_pickup_datetime::TIMESTAMP) AS hour
        FROM read_csv_auto('{path}')
        WHERE tip_amount > 0
    """

    if i == 0:
      con.execute(f"CREATE TABLE base_df AS {query}")
    else:
      con.execute(f"INSERT INTO base_df {query}")

tip_mean_per_hour = con.execute("""
    SELECT hour, AVG(tip_amount) AS tip_mean
    FROM base_df
    GROUP BY hour
    ORDER BY hour
""").fetchdf()

"""### Gorjeta média por Horário"""

print(tip_mean_per_hour)

"""### To Parquet"""

start = datetime.now()

def save_parquet():
  db.sql("""
      COPY (
          SELECT *
          FROM tip_mean_per_hour
      ) TO '/content/parquet_files/tip_mean_per_hour_duckdb.parquet' (FORMAT 'parquet');
    """)

mem_usage = memory_usage(save_parquet)

end = datetime.now()

time_in_sec = (end - start).total_seconds()

results_duckdb_df = pd.DataFrame({
  'lib': ['duckdb'],
  'max_memory_use': [max(mem_usage)],
  'min_memory_use': [min(mem_usage)],
  'total_memory_use': [max(mem_usage) - min(mem_usage)],
  'time_in_sec': [time_in_sec]
})

results_df = pd.concat([results_df, results_duckdb_df], ignore_index=True)

"""## Gráficos

### Tempo de Execução por Biblioteca
"""

plt.figure(figsize=(10, 6))
sns.barplot(data=results_df, x='lib', y='time_in_sec', palette='viridis')

plt.title('Tempo de Execução por Biblioteca')
plt.ylabel('Tempo (segundos)')
plt.xlabel('Biblioteca')
plt.tight_layout()
plt.show()

"""### Total de Memória por Biblioteca"""

plt.figure(figsize=(10, 6))
sns.barplot(data=results_df, x='lib', y='total_memory_use', palette='viridis')

plt.title('Total de Memória por Biblioteca')
plt.ylabel('Memória (MB)')
plt.xlabel('Biblioteca')
plt.tight_layout()
plt.show()

"""### Pico máximo de Memória por *Biblioteca*"""

plt.figure(figsize=(10, 6))
sns.barplot(data=results_df, x='lib', y='max_memory_use', palette='viridis')

plt.title('Pico máximo de Memória por Biblioteca')
plt.ylabel('Memória (MB)')
plt.xlabel('Biblioteca')
plt.tight_layout()
plt.show()